eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.200.2.32:8080/eureka/

spring:
  kafka:
    bootstrap-servers: 10.2.200.154:9092
  cloud:
    config:
      import-check.enabled: false

  application:
    name: Kafka-Server
