server:
  address: 10.200.2.170

custom-kafka1:
  bootStrapServer: 10.2.200.154.9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.200.2.32:8080/eureka/

spring:
  cloud:
    config:
      import-check.enabled: false

  application:
    name: Kafka-Server
    stream :
      bindings:
        cpu_input_channel:
          destination: TOPIC_CPU
        cpu-service-output:
          destination: MainCpuDataService
        ram_input_channel:
          destination: TOPIC_RAM
        ram-service-output:
          destination: MainCpuDataService
      kafka:
        streams:
          binder:
            brokers: localhost:9092
